import Image from "next/image";
import { PageIntro } from "@/components/PageIntro";
import { ResearchIntroPanel } from "@/components/ResearchIntroPanel";
import {
  publications,
  researchAreas,
  researchDirectionsIntro,
  researchDirectionsQuestion,
  type Publication,
  type ResearchArea
} from "@/lib/content";
import { withBasePath } from "@/lib/site-paths";

function publicationId(publication: Publication) {
  return `publication-${publication.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")}`;
}

function publicationHref(publication: Publication) {
  return withBasePath(`/publications/#${publicationId(publication)}`);
}

function relatedPublications(area: ResearchArea) {
  return (area.relatedPublicationTitles ?? [])
    .map((title) => publications.find((publication) => publication.title === title))
    .filter((publication): publication is Publication => Boolean(publication));
}

export default function ResearchPage() {
  return (
    <>
      <PageIntro
        eyebrow="Research"
        title="Metabolomics & Xenobiotic Metabolism"
        description="We aim to map the small molecules in our bodies and understand how food, microbes, and the environment shape them."
      />

      <section className="grid gap-4 px-5 py-10 sm:px-8 lg:py-14">
        <div className="mx-auto w-full max-w-7xl">
          <ResearchIntroPanel intro={researchDirectionsIntro} question={researchDirectionsQuestion} />
        </div>

        {researchAreas.map((area, index) => {
          const papers = relatedPublications(area);
          const figureOnLeft =
            area.slug === "mass-spectrometry-informatics" || area.slug === "microbial-xenobiotic-metabolism";
          const gradient = figureOnLeft
            ? "linear-gradient(270deg, rgba(255,255,255,0.99) 0%, rgba(255,255,255,0.95) 48%, rgba(255,255,255,0.74) 72%, rgba(255,255,255,0.18) 100%)"
            : "linear-gradient(90deg, rgba(255,255,255,0.99) 0%, rgba(255,255,255,0.95) 48%, rgba(255,255,255,0.74) 72%, rgba(255,255,255,0.18) 100%)";
          const labelPosition = figureOnLeft ? "left-4" : "right-4";

          return (
            <article
              key={area.slug}
              id={area.slug}
              className="relative mx-auto min-h-[500px] w-full max-w-7xl scroll-mt-28 overflow-hidden rounded-lg border border-line bg-white shadow-sm"
            >
              <Image
                src={withBasePath(area.image)}
                alt={`Scientific illustration for ${area.title}.`}
                fill
                sizes="(min-width: 1280px) 1152px, 100vw"
                className="object-contain"
                style={{ objectPosition: figureOnLeft ? "left center" : "right center" }}
              />
              <div className="absolute inset-0" style={{ background: gradient }} />
              <div className="absolute inset-0 bg-white/[0.85] lg:hidden" />
              <p
                className={`absolute bottom-4 ${labelPosition} z-20 text-[10px] font-semibold text-muted`}
              >
                Image generated by AI
              </p>
              <div className={`relative z-10 flex min-h-[500px] ${figureOnLeft ? "justify-end" : ""}`}>
                <div className="w-full max-w-3xl p-6 sm:p-8 lg:p-10">
                  <p className="text-sm font-semibold text-fudan">0{index + 1}</p>
                  <h2 className="mt-3 text-3xl font-semibold tracking-normal text-ink sm:text-4xl">
                    {area.title}
                  </h2>
                  <p className="mt-4 text-base leading-7 text-muted">{area.longDescription}</p>

                  {papers.length > 0 ? (
                    <div className="mt-6 border-t border-line pt-5">
                      <h3 className="text-sm font-semibold uppercase tracking-normal text-ink">Related Papers</h3>
                      <ul className="mt-3 space-y-3 text-sm leading-6 text-muted">
                        {papers.map((publication) => (
                          <li key={`${area.slug}-${publication.title}`}>
                            <a
                              href={publicationHref(publication)}
                              className="font-semibold text-fudan transition hover:text-ink"
                            >
                              {publication.title}
                            </a>
                            <span className="mt-0.5 block">
                              {publication.venue}, {publication.year}
                            </span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  ) : null}
                </div>
              </div>
            </article>
          );
        })}
      </section>
    </>
  );
}
